package co.com.miHotel.modelo.inmuebleHabitacion;
// Generated 05-may-2019 1:08:57 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import co.com.miHotel.modelo.habitacion.Habitacion;
import co.com.miHotel.modelo.habitacion.IncidenteHabitacion;
import co.com.miHotel.modelo.inmueble.Inmueble;

/**
 * InmuebleHabitacion generated by hbm2java
 */
@Entity
@Table(name = "inmueble_habitacion", schema = "public")
public class InmuebleHabitacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2045977154162714216L;
	
	private int idInmuebleHabitacion;
	private Habitacion habitacion;
	private Inmueble inmueble;
	private Set<IncidenteHabitacion> incidenteInmuebles = new HashSet<>();

	public InmuebleHabitacion() {
	}

	public InmuebleHabitacion(int idInmuebleHabitacion, Habitacion habitacion, Inmueble inmueble) {
		this.idInmuebleHabitacion = idInmuebleHabitacion;
		this.habitacion = habitacion;
		this.inmueble = inmueble;
	}

	public InmuebleHabitacion(int idInmuebleHabitacion, Habitacion habitacion, Inmueble inmueble,
			Set<IncidenteHabitacion> incidenteInmuebles) {
		this.idInmuebleHabitacion = idInmuebleHabitacion;
		this.habitacion = habitacion;
		this.inmueble = inmueble;
		this.incidenteInmuebles = incidenteInmuebles;
	}

	@Id

	@Column(name = "id_inmueble_habitacion", unique = true, nullable = false)
	public int getIdInmuebleHabitacion() {
		return this.idInmuebleHabitacion;
	}

	public void setIdInmuebleHabitacion(int idInmuebleHabitacion) {
		this.idInmuebleHabitacion = idInmuebleHabitacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_habitacion", nullable = false)
	public Habitacion getHabitacion() {
		return this.habitacion;
	}

	public void setHabitacion(Habitacion habitacion) {
		this.habitacion = habitacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_inmueble", nullable = false)
	public Inmueble getInmueble() {
		return this.inmueble;
	}

	public void setInmueble(Inmueble inmueble) {
		this.inmueble = inmueble;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inmuebleHabitacion")
	public Set<IncidenteHabitacion> getIncidenteInmuebles() {
		return this.incidenteInmuebles;
	}

	public void setIncidenteInmuebles(Set<IncidenteHabitacion> incidenteInmuebles) {
		this.incidenteInmuebles = incidenteInmuebles;
	}

}
