package modelo;
// Generated 02-may-2019 20:47:02 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoriaProducto generated by hbm2java
 */
@Entity
@Table(name = "categoria_producto", schema = "public")
public class CategoriaProducto implements java.io.Serializable {

	private int idCategoriaProducto;
	private String descripcion;
	private Set subcategoriaProductos = new HashSet(0);

	public CategoriaProducto() {
	}

	public CategoriaProducto(int idCategoriaProducto, String descripcion) {
		this.idCategoriaProducto = idCategoriaProducto;
		this.descripcion = descripcion;
	}

	public CategoriaProducto(int idCategoriaProducto, String descripcion, Set subcategoriaProductos) {
		this.idCategoriaProducto = idCategoriaProducto;
		this.descripcion = descripcion;
		this.subcategoriaProductos = subcategoriaProductos;
	}

	@Id

	@Column(name = "id_categoria_producto", unique = true, nullable = false)
	public int getIdCategoriaProducto() {
		return this.idCategoriaProducto;
	}

	public void setIdCategoriaProducto(int idCategoriaProducto) {
		this.idCategoriaProducto = idCategoriaProducto;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaProducto")
	public Set getSubcategoriaProductos() {
		return this.subcategoriaProductos;
	}

	public void setSubcategoriaProductos(Set subcategoriaProductos) {
		this.subcategoriaProductos = subcategoriaProductos;
	}

}
