package modelo;
// Generated 02-may-2019 20:47:02 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CategoriaInmueble generated by hbm2java
 */
@Entity
@Table(name = "categoria_inmueble", schema = "public")
public class CategoriaInmueble implements java.io.Serializable {

	private int idcategoriaInmueble;
	private String descripcion;

	public CategoriaInmueble() {
	}

	public CategoriaInmueble(int idcategoriaInmueble, String descripcion) {
		this.idcategoriaInmueble = idcategoriaInmueble;
		this.descripcion = descripcion;
	}

	@Id

	@Column(name = "idcategoria_inmueble", unique = true, nullable = false)
	public int getIdcategoriaInmueble() {
		return this.idcategoriaInmueble;
	}

	public void setIdcategoriaInmueble(int idcategoriaInmueble) {
		this.idcategoriaInmueble = idcategoriaInmueble;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
