package modelo;
// Generated 02-may-2019 20:47:02 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", schema = "public")
public class Producto implements java.io.Serializable {

	private int idProducto;
	private SubcategoriaProducto subcategoriaProducto;
	private String descripcion;
	private double precioUnitario;
	private int cantidad;
	private Serializable foto;
	private Set tiendas = new HashSet(0);

	public Producto() {
	}

	public Producto(int idProducto, SubcategoriaProducto subcategoriaProducto, String descripcion,
			double precioUnitario, int cantidad, Serializable foto) {
		this.idProducto = idProducto;
		this.subcategoriaProducto = subcategoriaProducto;
		this.descripcion = descripcion;
		this.precioUnitario = precioUnitario;
		this.cantidad = cantidad;
		this.foto = foto;
	}

	public Producto(int idProducto, SubcategoriaProducto subcategoriaProducto, String descripcion,
			double precioUnitario, int cantidad, Serializable foto, Set tiendas) {
		this.idProducto = idProducto;
		this.subcategoriaProducto = subcategoriaProducto;
		this.descripcion = descripcion;
		this.precioUnitario = precioUnitario;
		this.cantidad = cantidad;
		this.foto = foto;
		this.tiendas = tiendas;
	}

	@Id

	@Column(name = "id_producto", unique = true, nullable = false)
	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_subcategoria_producto", nullable = false)
	public SubcategoriaProducto getSubcategoriaProducto() {
		return this.subcategoriaProducto;
	}

	public void setSubcategoriaProducto(SubcategoriaProducto subcategoriaProducto) {
		this.subcategoriaProducto = subcategoriaProducto;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "precio_unitario", nullable = false, precision = 17, scale = 17)
	public double getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(double precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "foto", nullable = false)
	public Serializable getFoto() {
		return this.foto;
	}

	public void setFoto(Serializable foto) {
		this.foto = foto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set getTiendas() {
		return this.tiendas;
	}

	public void setTiendas(Set tiendas) {
		this.tiendas = tiendas;
	}

}
