package modelo;
// Generated 02-may-2019 20:47:02 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SubcategoriaProducto generated by hbm2java
 */
@Entity
@Table(name = "subcategoria_producto", schema = "public")
public class SubcategoriaProducto implements java.io.Serializable {

	private int idSubcategoriaProducto;
	private CategoriaProducto categoriaProducto;
	private MarcaProducto marcaProducto;
	private String descripcion;
	private Set productos = new HashSet(0);

	public SubcategoriaProducto() {
	}

	public SubcategoriaProducto(int idSubcategoriaProducto, CategoriaProducto categoriaProducto,
			MarcaProducto marcaProducto, String descripcion) {
		this.idSubcategoriaProducto = idSubcategoriaProducto;
		this.categoriaProducto = categoriaProducto;
		this.marcaProducto = marcaProducto;
		this.descripcion = descripcion;
	}

	public SubcategoriaProducto(int idSubcategoriaProducto, CategoriaProducto categoriaProducto,
			MarcaProducto marcaProducto, String descripcion, Set productos) {
		this.idSubcategoriaProducto = idSubcategoriaProducto;
		this.categoriaProducto = categoriaProducto;
		this.marcaProducto = marcaProducto;
		this.descripcion = descripcion;
		this.productos = productos;
	}

	@Id

	@Column(name = "id_subcategoria_producto", unique = true, nullable = false)
	public int getIdSubcategoriaProducto() {
		return this.idSubcategoriaProducto;
	}

	public void setIdSubcategoriaProducto(int idSubcategoriaProducto) {
		this.idSubcategoriaProducto = idSubcategoriaProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_categoria_producto", nullable = false)
	public CategoriaProducto getCategoriaProducto() {
		return this.categoriaProducto;
	}

	public void setCategoriaProducto(CategoriaProducto categoriaProducto) {
		this.categoriaProducto = categoriaProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_marca_producto", nullable = false)
	public MarcaProducto getMarcaProducto() {
		return this.marcaProducto;
	}

	public void setMarcaProducto(MarcaProducto marcaProducto) {
		this.marcaProducto = marcaProducto;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subcategoriaProducto")
	public Set getProductos() {
		return this.productos;
	}

	public void setProductos(Set productos) {
		this.productos = productos;
	}

}
