package modelo;
// Generated 02-may-2019 20:47:02 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tienda generated by hbm2java
 */
@Entity
@Table(name = "tienda", schema = "public")
public class Tienda implements java.io.Serializable {

	private int idCompra;
	private EstadoTienda estadoTienda;
	private Producto producto;
	private Reserva reserva;
	private int cantidad;
	private double precioTotal;

	public Tienda() {
	}

	public Tienda(int idCompra, EstadoTienda estadoTienda, Producto producto, Reserva reserva, int cantidad,
			double precioTotal) {
		this.idCompra = idCompra;
		this.estadoTienda = estadoTienda;
		this.producto = producto;
		this.reserva = reserva;
		this.cantidad = cantidad;
		this.precioTotal = precioTotal;
	}

	@Id

	@Column(name = "id_compra", unique = true, nullable = false)
	public int getIdCompra() {
		return this.idCompra;
	}

	public void setIdCompra(int idCompra) {
		this.idCompra = idCompra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_tienda", nullable = false)
	public EstadoTienda getEstadoTienda() {
		return this.estadoTienda;
	}

	public void setEstadoTienda(EstadoTienda estadoTienda) {
		this.estadoTienda = estadoTienda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_producto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_reserva", nullable = false)
	public Reserva getReserva() {
		return this.reserva;
	}

	public void setReserva(Reserva reserva) {
		this.reserva = reserva;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "precio_total", nullable = false, precision = 17, scale = 17)
	public double getPrecioTotal() {
		return this.precioTotal;
	}

	public void setPrecioTotal(double precioTotal) {
		this.precioTotal = precioTotal;
	}

}
