package co.com.miHotel.modelo.producto;
// Generated 05-may-2019 1:08:57 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MarcaProducto generated by hbm2java
 */
@Entity
@Table(name = "marca_producto", schema = "public")
public class MarcaProducto implements java.io.Serializable {

	private int idMarcaProducto;
	private String descripcion;
	private Set subcategoriaProductos = new HashSet(0);

	public MarcaProducto() {
	}

	public MarcaProducto(int idMarcaProducto, String descripcion) {
		this.idMarcaProducto = idMarcaProducto;
		this.descripcion = descripcion;
	}

	public MarcaProducto(int idMarcaProducto, String descripcion, Set subcategoriaProductos) {
		this.idMarcaProducto = idMarcaProducto;
		this.descripcion = descripcion;
		this.subcategoriaProductos = subcategoriaProductos;
	}

	@Id

	@Column(name = "id_marca_producto", unique = true, nullable = false)
	public int getIdMarcaProducto() {
		return this.idMarcaProducto;
	}

	public void setIdMarcaProducto(int idMarcaProducto) {
		this.idMarcaProducto = idMarcaProducto;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marcaProducto")
	public Set getSubcategoriaProductos() {
		return this.subcategoriaProductos;
	}

	public void setSubcategoriaProductos(Set subcategoriaProductos) {
		this.subcategoriaProductos = subcategoriaProductos;
	}

}
