package co.com.miHotel.modelo.producto;
// Generated 05-may-2019 1:08:57 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import co.com.miHotel.modelo.tienda.Tienda;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", schema = "public")
public class Producto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1584583244347605583L;

	private int idProducto;
	private SubcategoriaProducto subcategoriaProducto;
	private String descripcion;
	private double precioUnitario;
	private int cantidad;
	private String foto;
	private Set<Tienda> tiendas = new HashSet<>();

	public Producto() {
	}

	public Producto(int idProducto, SubcategoriaProducto subcategoriaProducto, String descripcion,
			double precioUnitario, int cantidad) {
		this.idProducto = idProducto;
		this.subcategoriaProducto = subcategoriaProducto;
		this.descripcion = descripcion;
		this.precioUnitario = precioUnitario;
		this.cantidad = cantidad;
	}

	public Producto(int idProducto, SubcategoriaProducto subcategoriaProducto, String descripcion,
			double precioUnitario, int cantidad, String foto, Set<Tienda> tiendas) {
		this.idProducto = idProducto;
		this.subcategoriaProducto = subcategoriaProducto;
		this.descripcion = descripcion;
		this.precioUnitario = precioUnitario;
		this.cantidad = cantidad;
		this.foto = foto;
		this.tiendas = tiendas;
	}

	@Id

	@Column(name = "id_producto", unique = true, nullable = false)
	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_subcategoria_producto", nullable = false)
	public SubcategoriaProducto getSubcategoriaProducto() {
		return this.subcategoriaProducto;
	}

	public void setSubcategoriaProducto(SubcategoriaProducto subcategoriaProducto) {
		this.subcategoriaProducto = subcategoriaProducto;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "precio_unitario", nullable = false, precision = 17, scale = 17)
	public double getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(double precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "foto", length = 200)
	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<Tienda> getTiendas() {
		return this.tiendas;
	}

	public void setTiendas(Set<Tienda> tiendas) {
		this.tiendas = tiendas;
	}

}
