package co.com.miHotel.modelo.producto;
// Generated 05-may-2019 1:08:57 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SubcategoriaProducto generated by hbm2java
 */
@Entity
@Table(name = "subcategoria_producto", schema = "public")
public class SubcategoriaProducto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2314708220877522783L;

	private int idSubcategoriaProducto;
	private CategoriaProducto categoriaProducto;
	private MarcaProducto marcaProducto;
	private String descripcion;
	private Set<Producto> productos = new HashSet<>();

	public SubcategoriaProducto() {
	}

	public SubcategoriaProducto(int idSubcategoriaProducto, CategoriaProducto categoriaProducto,
			MarcaProducto marcaProducto, String descripcion) {
		this.idSubcategoriaProducto = idSubcategoriaProducto;
		this.categoriaProducto = categoriaProducto;
		this.marcaProducto = marcaProducto;
		this.descripcion = descripcion;
	}

	public SubcategoriaProducto(int idSubcategoriaProducto, CategoriaProducto categoriaProducto,
			MarcaProducto marcaProducto, String descripcion, Set<Producto> productos) {
		this.idSubcategoriaProducto = idSubcategoriaProducto;
		this.categoriaProducto = categoriaProducto;
		this.marcaProducto = marcaProducto;
		this.descripcion = descripcion;
		this.productos = productos;
	}

	@Id

	@Column(name = "id_subcategoria_producto", unique = true, nullable = false)
	public int getIdSubcategoriaProducto() {
		return this.idSubcategoriaProducto;
	}

	public void setIdSubcategoriaProducto(int idSubcategoriaProducto) {
		this.idSubcategoriaProducto = idSubcategoriaProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_categoria_producto", nullable = false)
	public CategoriaProducto getCategoriaProducto() {
		return this.categoriaProducto;
	}

	public void setCategoriaProducto(CategoriaProducto categoriaProducto) {
		this.categoriaProducto = categoriaProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_marca_producto", nullable = false)
	public MarcaProducto getMarcaProducto() {
		return this.marcaProducto;
	}

	public void setMarcaProducto(MarcaProducto marcaProducto) {
		this.marcaProducto = marcaProducto;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subcategoriaProducto")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}
