package co.com.miHotel.modelo.inmueble ;
// Generated 05-may-2019 1:08:57 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoInmueble generated by hbm2java
 */
@Entity
@Table(name = "estado_inmueble", schema = "public")
public class EstadoInmueble implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5605939050575245175L;
	
	private int idEstadoInmueble;
	private String descripcion;
	private Set<Inmueble> inmuebles = new HashSet<>();

	public EstadoInmueble() {
	}

	public EstadoInmueble(int idEstadoInmueble, String descripcion) {
		this.idEstadoInmueble = idEstadoInmueble;
		this.descripcion = descripcion;
	}

	public EstadoInmueble(int idEstadoInmueble, String descripcion, Set<Inmueble> inmuebles) {
		this.idEstadoInmueble = idEstadoInmueble;
		this.descripcion = descripcion;
		this.inmuebles = inmuebles;
	}

	@Id

	@Column(name = "id_estado_inmueble", unique = true, nullable = false)
	public int getIdEstadoInmueble() {
		return this.idEstadoInmueble;
	}

	public void setIdEstadoInmueble(int idEstadoInmueble) {
		this.idEstadoInmueble = idEstadoInmueble;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoInmueble")
	public Set<Inmueble> getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Set<Inmueble> inmuebles) {
		this.inmuebles = inmuebles;
	}

}
