package co.com.miHotel.modelo.inmueble ;
// Generated 05-may-2019 1:08:57 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inmueble generated by hbm2java
 */
@Entity
@Table(name = "inmueble", schema = "public")
public class Inmueble implements java.io.Serializable {

	private int idInmueble;
	private EstadoInmueble estadoInmueble;
	private TipoInmueble tipoInmueble;
	private String codigo;
	private Date fechaIngreso;
	private double precio;
	private String descripcion;
	private String foto;
	private Set tipoInmuebles = new HashSet(0);
	private Set inmuebleHabitacions = new HashSet(0);

	public Inmueble() {
	}

	public Inmueble(int idInmueble, EstadoInmueble estadoInmueble, TipoInmueble tipoInmueble, String codigo,
			Date fechaIngreso, double precio, String descripcion) {
		this.idInmueble = idInmueble;
		this.estadoInmueble = estadoInmueble;
		this.tipoInmueble = tipoInmueble;
		this.codigo = codigo;
		this.fechaIngreso = fechaIngreso;
		this.precio = precio;
		this.descripcion = descripcion;
	}

	public Inmueble(int idInmueble, EstadoInmueble estadoInmueble, TipoInmueble tipoInmueble, String codigo,
			Date fechaIngreso, double precio, String descripcion, String foto, Set tipoInmuebles,
			Set inmuebleHabitacions) {
		this.idInmueble = idInmueble;
		this.estadoInmueble = estadoInmueble;
		this.tipoInmueble = tipoInmueble;
		this.codigo = codigo;
		this.fechaIngreso = fechaIngreso;
		this.precio = precio;
		this.descripcion = descripcion;
		this.foto = foto;
		this.tipoInmuebles = tipoInmuebles;
		this.inmuebleHabitacions = inmuebleHabitacions;
	}

	@Id

	@Column(name = "id_inmueble", unique = true, nullable = false)
	public int getIdInmueble() {
		return this.idInmueble;
	}

	public void setIdInmueble(int idInmueble) {
		this.idInmueble = idInmueble;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_inmueble", nullable = false)
	public EstadoInmueble getEstadoInmueble() {
		return this.estadoInmueble;
	}

	public void setEstadoInmueble(EstadoInmueble estadoInmueble) {
		this.estadoInmueble = estadoInmueble;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_inmueble", nullable = false)
	public TipoInmueble getTipoInmueble() {
		return this.tipoInmueble;
	}

	public void setTipoInmueble(TipoInmueble tipoInmueble) {
		this.tipoInmueble = tipoInmueble;
	}

	@Column(name = "codigo", nullable = false, length = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ingreso", nullable = false, length = 13)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "precio", nullable = false, precision = 17, scale = 17)
	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "foto", length = 200)
	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inmueble")
	public Set getTipoInmuebles() {
		return this.tipoInmuebles;
	}

	public void setTipoInmuebles(Set tipoInmuebles) {
		this.tipoInmuebles = tipoInmuebles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inmueble")
	public Set getInmuebleHabitacions() {
		return this.inmuebleHabitacions;
	}

	public void setInmuebleHabitacions(Set inmuebleHabitacions) {
		this.inmuebleHabitacions = inmuebleHabitacions;
	}

}
