package co.com.miHotel.modelo.inmueble ;
// Generated 05-may-2019 1:08:57 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MarcaInmueble generated by hbm2java
 */
@Entity
@Table(name = "marca_inmueble", schema = "public")
public class MarcaInmueble implements java.io.Serializable {

	private int idMarcaInmueble;
	private String descripcion;
	private Set tipoInmuebles = new HashSet(0);

	public MarcaInmueble() {
	}

	public MarcaInmueble(int idMarcaInmueble, String descripcion) {
		this.idMarcaInmueble = idMarcaInmueble;
		this.descripcion = descripcion;
	}

	public MarcaInmueble(int idMarcaInmueble, String descripcion, Set tipoInmuebles) {
		this.idMarcaInmueble = idMarcaInmueble;
		this.descripcion = descripcion;
		this.tipoInmuebles = tipoInmuebles;
	}

	@Id

	@Column(name = "id_marca_inmueble", unique = true, nullable = false)
	public int getIdMarcaInmueble() {
		return this.idMarcaInmueble;
	}

	public void setIdMarcaInmueble(int idMarcaInmueble) {
		this.idMarcaInmueble = idMarcaInmueble;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marcaInmueble")
	public Set getTipoInmuebles() {
		return this.tipoInmuebles;
	}

	public void setTipoInmuebles(Set tipoInmuebles) {
		this.tipoInmuebles = tipoInmuebles;
	}

}
