package co.com.miHotel.modelo.inmueble;
// Generated 05-may-2019 1:08:57 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoInmueble generated by hbm2java
 */
@Entity
@Table(name = "tipo_inmueble", schema = "public")
public class TipoInmueble implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6012749249617759403L;

	private int idTipoInmueble;
	private Inmueble inmueble;
	private MarcaInmueble marcaInmueble;
	private String descripcion;
	private int cantidad;
	private Set<Inmueble> inmuebles = new HashSet<>();

	public TipoInmueble() {
	}

	public TipoInmueble(int idTipoInmueble, Inmueble inmueble, MarcaInmueble marcaInmueble, String descripcion,
			int cantidad) {
		this.idTipoInmueble = idTipoInmueble;
		this.inmueble = inmueble;
		this.marcaInmueble = marcaInmueble;
		this.descripcion = descripcion;
		this.cantidad = cantidad;
	}

	public TipoInmueble(int idTipoInmueble, Inmueble inmueble, MarcaInmueble marcaInmueble, String descripcion,
			int cantidad, Set<Inmueble> inmuebles) {
		this.idTipoInmueble = idTipoInmueble;
		this.inmueble = inmueble;
		this.marcaInmueble = marcaInmueble;
		this.descripcion = descripcion;
		this.cantidad = cantidad;
		this.inmuebles = inmuebles;
	}

	@Id

	@Column(name = "id_tipo_inmueble", unique = true, nullable = false)
	public int getIdTipoInmueble() {
		return this.idTipoInmueble;
	}

	public void setIdTipoInmueble(int idTipoInmueble) {
		this.idTipoInmueble = idTipoInmueble;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_inmueble", nullable = false)
	public Inmueble getInmueble() {
		return this.inmueble;
	}

	public void setInmueble(Inmueble inmueble) {
		this.inmueble = inmueble;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_marca_inmueble", nullable = false)
	public MarcaInmueble getMarcaInmueble() {
		return this.marcaInmueble;
	}

	public void setMarcaInmueble(MarcaInmueble marcaInmueble) {
		this.marcaInmueble = marcaInmueble;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoInmueble")
	public Set<Inmueble> getInmuebles() {
		return this.inmuebles;
	}

	public void setInmuebles(Set<Inmueble> inmuebles) {
		this.inmuebles = inmuebles;
	}

}
