package co.com.miHotel.modelo.habitacion;
// Generated 05-may-2019 1:08:57 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoHabitacion generated by hbm2java
 */
@Entity
@Table(name = "estado_habitacion", schema = "public")
public class EstadoHabitacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idEstadoHabitacion;
	private String descripcion;
	private Set habitacions = new HashSet(0);

	public EstadoHabitacion() {
	}

	public EstadoHabitacion(int idEstadoHabitacion, String descripcion) {
		this.idEstadoHabitacion = idEstadoHabitacion;
		this.descripcion = descripcion;
	}

	public EstadoHabitacion(int idEstadoHabitacion, String descripcion, Set habitacions) {
		this.idEstadoHabitacion = idEstadoHabitacion;
		this.descripcion = descripcion;
		this.habitacions = habitacions;
	}

	@Id

	@Column(name = "id_estado_habitacion", unique = true, nullable = false)
	public int getIdEstadoHabitacion() {
		return this.idEstadoHabitacion;
	}

	public void setIdEstadoHabitacion(int idEstadoHabitacion) {
		this.idEstadoHabitacion = idEstadoHabitacion;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoHabitacion")
	public Set getHabitacions() {
		return this.habitacions;
	}

	public void setHabitacions(Set habitacions) {
		this.habitacions = habitacions;
	}

}
