package co.com.miHotel.modelo.habitacion;
// Generated 05-may-2019 1:08:57 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Habitacion generated by hbm2java
 */
@Entity
@Table(name = "habitacion", schema = "public")
public class Habitacion implements java.io.Serializable {

	private int idHabitacion;
	private EstadoHabitacion estadoHabitacion;
	private TipoHabitacion tipoHabitacion;
	private int piso;
	private String numeroHabitacion;
	private double precioMaximo;
	private double precioMinimo;
	private Set incidenteHabitacions = new HashSet(0);
	private Set inmuebleHabitacions = new HashSet(0);
	private Set reservas = new HashSet(0);

	public Habitacion() {
	}

	public Habitacion(int idHabitacion, EstadoHabitacion estadoHabitacion, TipoHabitacion tipoHabitacion, int piso,
			String numeroHabitacion, double precioMaximo, double precioMinimo) {
		this.idHabitacion = idHabitacion;
		this.estadoHabitacion = estadoHabitacion;
		this.tipoHabitacion = tipoHabitacion;
		this.piso = piso;
		this.numeroHabitacion = numeroHabitacion;
		this.precioMaximo = precioMaximo;
		this.precioMinimo = precioMinimo;
	}

	public Habitacion(int idHabitacion, EstadoHabitacion estadoHabitacion, TipoHabitacion tipoHabitacion, int piso,
			String numeroHabitacion, double precioMaximo, double precioMinimo, Set incidenteHabitacions,
			Set inmuebleHabitacions, Set reservas) {
		this.idHabitacion = idHabitacion;
		this.estadoHabitacion = estadoHabitacion;
		this.tipoHabitacion = tipoHabitacion;
		this.piso = piso;
		this.numeroHabitacion = numeroHabitacion;
		this.precioMaximo = precioMaximo;
		this.precioMinimo = precioMinimo;
		this.incidenteHabitacions = incidenteHabitacions;
		this.inmuebleHabitacions = inmuebleHabitacions;
		this.reservas = reservas;
	}

	@Id

	@Column(name = "id_habitacion", unique = true, nullable = false)
	public int getIdHabitacion() {
		return this.idHabitacion;
	}

	public void setIdHabitacion(int idHabitacion) {
		this.idHabitacion = idHabitacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_habitacion", nullable = false)
	public EstadoHabitacion getEstadoHabitacion() {
		return this.estadoHabitacion;
	}

	public void setEstadoHabitacion(EstadoHabitacion estadoHabitacion) {
		this.estadoHabitacion = estadoHabitacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_habitacion", nullable = false)
	public TipoHabitacion getTipoHabitacion() {
		return this.tipoHabitacion;
	}

	public void setTipoHabitacion(TipoHabitacion tipoHabitacion) {
		this.tipoHabitacion = tipoHabitacion;
	}

	@Column(name = "piso", nullable = false)
	public int getPiso() {
		return this.piso;
	}

	public void setPiso(int piso) {
		this.piso = piso;
	}

	@Column(name = "numero_habitacion", nullable = false, length = 10)
	public String getNumeroHabitacion() {
		return this.numeroHabitacion;
	}

	public void setNumeroHabitacion(String numeroHabitacion) {
		this.numeroHabitacion = numeroHabitacion;
	}

	@Column(name = "precio_maximo", nullable = false, precision = 17, scale = 17)
	public double getPrecioMaximo() {
		return this.precioMaximo;
	}

	public void setPrecioMaximo(double precioMaximo) {
		this.precioMaximo = precioMaximo;
	}

	@Column(name = "precio_minimo", nullable = false, precision = 17, scale = 17)
	public double getPrecioMinimo() {
		return this.precioMinimo;
	}

	public void setPrecioMinimo(double precioMinimo) {
		this.precioMinimo = precioMinimo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "habitacion")
	public Set getIncidenteHabitacions() {
		return this.incidenteHabitacions;
	}

	public void setIncidenteHabitacions(Set incidenteHabitacions) {
		this.incidenteHabitacions = incidenteHabitacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "habitacion")
	public Set getInmuebleHabitacions() {
		return this.inmuebleHabitacions;
	}

	public void setInmuebleHabitacions(Set inmuebleHabitacions) {
		this.inmuebleHabitacions = inmuebleHabitacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "habitacion")
	public Set getReservas() {
		return this.reservas;
	}

	public void setReservas(Set reservas) {
		this.reservas = reservas;
	}

}
