package co.com.miHotel.modelo.habitacion;
// Generated 05-may-2019 1:08:57 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoHabitacion generated by hbm2java
 */
@Entity
@Table(name = "tipo_habitacion", schema = "public")
public class TipoHabitacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4576735145416918556L;

	private int idTipoHabitacion;
	private String descripcion;
	private Set<Habitacion> habitacions = new HashSet<>();

	public TipoHabitacion() {
	}

	public TipoHabitacion(int idTipoHabitacion, String descripcion) {
		this.idTipoHabitacion = idTipoHabitacion;
		this.descripcion = descripcion;
	}

	public TipoHabitacion(int idTipoHabitacion, String descripcion, Set<Habitacion> habitacions) {
		this.idTipoHabitacion = idTipoHabitacion;
		this.descripcion = descripcion;
		this.habitacions = habitacions;
	}

	@Id

	@Column(name = "id_tipo_habitacion", unique = true, nullable = false)
	public int getIdTipoHabitacion() {
		return this.idTipoHabitacion;
	}

	public void setIdTipoHabitacion(int idTipoHabitacion) {
		this.idTipoHabitacion = idTipoHabitacion;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoHabitacion")
	public Set<Habitacion> getHabitacions() {
		return this.habitacions;
	}

	public void setHabitacions(Set<Habitacion> habitacions) {
		this.habitacions = habitacions;
	}

}
