package co.com.miHotel.modelo.incidente;
// Generated 05-may-2019 1:08:57 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import co.com.miHotel.modelo.habitacion.IncidenteHabitacion;
import co.com.miHotel.modelo.inmueble.IncidenteInmueble;

/**
 * EstadoIncidencia generated by hbm2java
 */
@Entity
@Table(name = "estado_incidencia", schema = "public")
public class EstadoIncidencia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5471978010750383855L;
	
	private int idEstadoIncidencia;
	private String descripcion;
	private Set<IncidenteInmueble> incidenteInmuebles = new HashSet<>();
	private Set<IncidenteHabitacion> incidenteHabitacions = new HashSet<>();

	public EstadoIncidencia() {
	}

	public EstadoIncidencia(int idEstadoIncidencia, String descripcion) {
		this.idEstadoIncidencia = idEstadoIncidencia;
		this.descripcion = descripcion;
	}

	public EstadoIncidencia(int idEstadoIncidencia, String descripcion, Set<IncidenteInmueble> incidenteInmuebles,
			Set<IncidenteHabitacion> incidenteHabitacions) {
		this.idEstadoIncidencia = idEstadoIncidencia;
		this.descripcion = descripcion;
		this.incidenteInmuebles = incidenteInmuebles;
		this.incidenteHabitacions = incidenteHabitacions;
	}

	@Id

	@Column(name = "id_estado_incidencia", unique = true, nullable = false)
	public int getIdEstadoIncidencia() {
		return this.idEstadoIncidencia;
	}

	public void setIdEstadoIncidencia(int idEstadoIncidencia) {
		this.idEstadoIncidencia = idEstadoIncidencia;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoIncidencia")
	public Set<IncidenteInmueble> getIncidenteInmuebles() {
		return this.incidenteInmuebles;
	}

	public void setIncidenteInmuebles(Set<IncidenteInmueble> incidenteInmuebles) {
		this.incidenteInmuebles = incidenteInmuebles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoIncidencia")
	public Set<IncidenteHabitacion> getIncidenteHabitacions() {
		return this.incidenteHabitacions;
	}

	public void setIncidenteHabitacions(Set<IncidenteHabitacion> incidenteHabitacions) {
		this.incidenteHabitacions = incidenteHabitacions;
	}

}
