package co.com.miHotel.modelo.persona;
// Generated 05-may-2019 1:08:57 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import co.com.miHotel.modelo.login.Login;
import co.com.miHotel.modelo.login.Rol;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona", schema = "public")
public class Persona implements java.io.Serializable {

	private int idPersona;
	private EstadoPersona estadoPersona;
	private Rol rol;
	private TipoDocumento tipoDocumento;
	private String numeroDocumento;
	private String primerNombre;
	private String segundoNombre;
	private String primerApellido;
	private String segundoApellido;
	private int telefono;
	private String correo;
	private Date fechaNacimiento;
	private Short edad;
	private Set reservas = new HashSet(0);
	private Login login;

	public Persona() {
	}

	public Persona(int idPersona, EstadoPersona estadoPersona, Rol rol, TipoDocumento tipoDocumento,
			String numeroDocumento, String primerNombre, String primerApellido, int telefono, Date fechaNacimiento) {
		this.idPersona = idPersona;
		this.estadoPersona = estadoPersona;
		this.rol = rol;
		this.tipoDocumento = tipoDocumento;
		this.numeroDocumento = numeroDocumento;
		this.primerNombre = primerNombre;
		this.primerApellido = primerApellido;
		this.telefono = telefono;
		this.fechaNacimiento = fechaNacimiento;
	}

	public Persona(int idPersona, EstadoPersona estadoPersona, Rol rol, TipoDocumento tipoDocumento,
			String numeroDocumento, String primerNombre, String segundoNombre, String primerApellido,
			String segundoApellido, int telefono, String correo, Date fechaNacimiento, Short edad, Set reservas,
			Login login) {
		this.idPersona = idPersona;
		this.estadoPersona = estadoPersona;
		this.rol = rol;
		this.tipoDocumento = tipoDocumento;
		this.numeroDocumento = numeroDocumento;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.telefono = telefono;
		this.correo = correo;
		this.fechaNacimiento = fechaNacimiento;
		this.edad = edad;
		this.reservas = reservas;
		this.login = login;
	}

	@Id

	@Column(name = "id_persona", unique = true, nullable = false)
	public int getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(int idPersona) {
		this.idPersona = idPersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_persona", nullable = false)
	public EstadoPersona getEstadoPersona() {
		return this.estadoPersona;
	}

	public void setEstadoPersona(EstadoPersona estadoPersona) {
		this.estadoPersona = estadoPersona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_documento", nullable = false)
	public TipoDocumento getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "numero_documento", nullable = false, length = 20)
	public String getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	@Column(name = "primer_nombre", nullable = false)
	public String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(String primerNombre) {
		this.primerNombre = primerNombre;
	}

	@Column(name = "segundo_nombre")
	public String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	@Column(name = "primer_apellido", nullable = false)
	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	@Column(name = "segundo_apellido")
	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	@Column(name = "telefono", nullable = false)
	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	@Column(name = "correo", length = 100)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", nullable = false, length = 13)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "edad")
	public Short getEdad() {
		return this.edad;
	}

	public void setEdad(Short edad) {
		this.edad = edad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public Set getReservas() {
		return this.reservas;
	}

	public void setReservas(Set reservas) {
		this.reservas = reservas;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "persona")
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

}
