package co.com.miHotel.modelo.persona;
// Generated 05-may-2019 1:08:57 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoDocumento generated by hbm2java
 */
@Entity
@Table(name = "tipo_documento", schema = "public")
public class TipoDocumento implements java.io.Serializable {

	private int idTipoDocumento;
	private String descripcion;
	private Set personas = new HashSet(0);

	public TipoDocumento() {
	}

	public TipoDocumento(int idTipoDocumento, String descripcion) {
		this.idTipoDocumento = idTipoDocumento;
		this.descripcion = descripcion;
	}

	public TipoDocumento(int idTipoDocumento, String descripcion, Set personas) {
		this.idTipoDocumento = idTipoDocumento;
		this.descripcion = descripcion;
		this.personas = personas;
	}

	@Id

	@Column(name = "id_tipo_documento", unique = true, nullable = false)
	public int getIdTipoDocumento() {
		return this.idTipoDocumento;
	}

	public void setIdTipoDocumento(int idTipoDocumento) {
		this.idTipoDocumento = idTipoDocumento;
	}

	@Column(name = "descripcion", nullable = false, length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDocumento")
	public Set getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set personas) {
		this.personas = personas;
	}

}
