package co.com.miHotel.modelo.tienda;
// Generated 05-may-2019 1:08:57 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoTienda generated by hbm2java
 */
@Entity
@Table(name = "estado_tienda", schema = "public")
public class EstadoTienda implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 736673244051074460L;

	private int idEstadoTienda;
	private String descripcion;
	private Set<Tienda> tiendas = new HashSet<>();

	public EstadoTienda() {
	}

	public EstadoTienda(int idEstadoTienda, String descripcion) {
		this.idEstadoTienda = idEstadoTienda;
		this.descripcion = descripcion;
	}

	public EstadoTienda(int idEstadoTienda, String descripcion, Set<Tienda> tiendas) {
		this.idEstadoTienda = idEstadoTienda;
		this.descripcion = descripcion;
		this.tiendas = tiendas;
	}

	@Id

	@Column(name = "id_estado_tienda", unique = true, nullable = false)
	public int getIdEstadoTienda() {
		return this.idEstadoTienda;
	}

	public void setIdEstadoTienda(int idEstadoTienda) {
		this.idEstadoTienda = idEstadoTienda;
	}

	@Column(name = "descripcion", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoTienda")
	public Set<Tienda> getTiendas() {
		return this.tiendas;
	}

	public void setTiendas(Set<Tienda> tiendas) {
		this.tiendas = tiendas;
	}

}
